with open(r'C:\Users\Syed Asrar\bachelor-meal-plan\meals.js', 'r', encoding='utf-8') as f:
    content = f.read()

NEW = r"""
{id:'lm9',type:'lunch',effort:'medium',time:25,protein:24,calories:420,emoji:'🐟',
name:'Fish Fry + Rice',nameTA:'மீன் வறுவல் சாதம்',nameUR:'مچھلی فرائی چاول',
equipment:['induction','frying pan'],nightPrep:false,
ingredients:[
  {emoji:'🐟',name:'Fish fillets (surmai/pomfret/tilapia)',nameTA:'மீன்',nameUR:'مچھلی',qty:150,unit:'g'},
  {emoji:'🍚',name:'Cooked rice',nameTA:'சாதம்',nameUR:'چاول',qty:1.5,unit:'cups'},
  {emoji:'🔴',name:'Chili powder',nameTA:'மிளகாய் பொடி',nameUR:'لال مرچ',qty:1,unit:'tsp'},
  {emoji:'🟡',name:'Turmeric',nameTA:'மஞ்சள்',nameUR:'ہلدی',qty:0.25,unit:'tsp'},
  {emoji:'🌿',name:'Cumin + fennel (saunf) powder',nameTA:'சீரகம் சோம்பு',nameUR:'زیرہ سونف',qty:0.5,unit:'tsp each'},
  {emoji:'🍋',name:'Lemon juice',nameTA:'எலுமிச்சை',nameUR:'لیموں',qty:1,unit:'tbsp'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.75,unit:'tsp'},
],
steps:[
  {text:'Clean fish. Score 2–3 cuts on each side. Marinate with chili powder + turmeric + cumin + fennel + salt + lemon juice. Rest 15 min.',timer:900},
  {text:'Heat frying pan on V-Guard **Deep Fry** preset. Add oil (shallow fry — 0.5 inch depth).',timer:120},
  {text:'When oil is hot, slide fish pieces in carefully. Do not disturb for 3–4 min until bottom crust is deep golden.',timer:240},
  {text:'Flip gently using flat spatula. Fry other side 2–3 min. Fish should be crispy outside, cooked through. Drain on paper.',timer:180},
  {text:'Serve crispy fish alongside plain rice. Add onion rings + lemon wedge on side.',timer:0},
],
tip:'Surmai (king fish) or pomfret from Koyambedu fish market is best. Tilapia is cheapest (₹80–100/250g). Dry fish thoroughly before frying — water causes oil to splatter dangerously.',
video:'fish fry recipe south Indian style crispy',
},

{id:'lm10',type:'lunch',effort:'medium',time:30,protein:18,calories:400,emoji:'🦐',
name:'Prawn Rice',nameTA:'இறால் சாதம்',nameUR:'جھینگا چاول',
equipment:['induction','smart pot'],nightPrep:false,
ingredients:[
  {emoji:'🦐',name:'Prawns (cleaned)',nameTA:'இறால்',nameUR:'جھینگا',qty:150,unit:'g'},
  {emoji:'🍚',name:'Basmati rice',nameTA:'பாஸ்மதி',nameUR:'باسمتی',qty:0.75,unit:'cup'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:1,unit:'medium'},
  {emoji:'🍅',name:'Tomato',nameTA:'தக்காளி',nameUR:'ٹماٹر',qty:1,unit:'medium'},
  {emoji:'🫙',name:'Ginger-garlic paste',nameTA:'இஞ்சி பூண்டு',nameUR:'ادرک لہسن',qty:1,unit:'tsp'},
  {emoji:'🔴',name:'Chili powder + garam masala',nameTA:'மிளகாய் கரம் மசாலா',nameUR:'مرچ گرم مسالا',qty:0.5,unit:'tsp each'},
  {emoji:'🌿',name:'Mint + coriander leaves',nameTA:'புதினா கொத்தமல்லி',nameUR:'پدینہ دھنیا',qty:1,unit:'tbsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.75,unit:'tsp'},
],
steps:[
  {text:'Marinate prawns: chili powder + turmeric (0.25 tsp) + salt + lemon juice. Rest while you prep.',timer:0},
  {text:'Press **Sauté** → **Start** on Smart Pot. Add 1.5 tsp oil. Fry onion 3 min until golden. Add ginger-garlic paste, stir 30 sec. Add tomato + spices + salt. Cook 2 min. Press **Cancel**.',timer:360},
  {text:'Add washed rice + prawns + mint + 1.5 cups water. Stir.',timer:0},
  {text:'Close lid. Press **Pressure Cook** → set 6 min → **Start**. Quick release after cooking.',timer:360},
  {text:'Open. Gently fluff. Garnish with coriander. Serve hot.',timer:0},
],
tip:'Prawns cook very fast — do not increase pressure cooking time or they become rubbery. Medium-sized prawns from Koyambedu market cost ₹200–250/250g. Clean and devein properly.',
video:'prawn rice recipe one pot pressure cooker',
},

{id:'lm11',type:'lunch',effort:'medium',time:30,protein:26,calories:430,emoji:'🍛',
name:'Chicken Korma + Rice',nameTA:'சிக்கன் குர்மா சாதம்',nameUR:'چکن قورمہ چاول',
equipment:['smart pot'],nightPrep:false,
ingredients:[
  {emoji:'🍗',name:'Boneless chicken (cubed)',nameTA:'சிக்கன்',nameUR:'مرغی',qty:200,unit:'g'},
  {emoji:'🍚',name:'Cooked rice',nameTA:'சாதம்',nameUR:'چاول',qty:1.5,unit:'cups'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:1,unit:'medium'},
  {emoji:'🥛',name:'Coconut milk (canned)',nameTA:'தேங்காய் பால்',nameUR:'ناریل کا دودھ',qty:100,unit:'ml'},
  {emoji:'🌰',name:'Cashews (paste: blend 6 cashews + 2 tbsp water)',nameTA:'முந்திரி',nameUR:'کاجو',qty:6,unit:'nos'},
  {emoji:'🫙',name:'Ginger-garlic paste',nameTA:'இஞ்சி பூண்டு',nameUR:'ادرک لہسن',qty:1,unit:'tsp'},
  {emoji:'🔴',name:'Coriander + garam masala + chili powder',nameTA:'கொத்தமல்லி மசாலா',nameUR:'دھنیا مسالا مرچ',qty:0.5,unit:'tsp each'},
  {emoji:'🧂',name:'Salt + coriander leaves',nameTA:'உப்பு',nameUR:'نمک دھنیا',qty:0.75,unit:'tsp'},
],
steps:[
  {text:'Blend cashews + 2 tbsp water in NutriPro blender to smooth paste. Set aside.',timer:0},
  {text:'Press **Sauté** → **Start** on Smart Pot. Add 1.5 tsp oil. Fry onion until golden (3 min). Add ginger-garlic paste (30 sec). Add coriander + garam masala + chili powder + salt. Stir 1 min. Press **Cancel**.',timer:300},
  {text:'Add chicken + cashew paste + coconut milk + 100ml water. Close lid. Press **Meat** → 10 min → **Start**.',timer:600},
  {text:'Natural release 5 min. Open. Stir. Korma should be creamy and thick. Garnish with coriander.',timer:300},
  {text:'Serve korma over rice.',timer:0},
],
tip:'Cashew paste gives a naturally creamy texture without cream. For richer flavor, fry the onions until deep golden brown. Korma should be mild and aromatic, not spicy.',
video:'chicken korma recipe South Indian creamy',
},

{id:'lm12',type:'lunch',effort:'medium',time:25,protein:28,calories:420,emoji:'⚫',
name:'Chicken Pepper Rice',nameTA:'சிக்கன் மிளகு சாதம்',nameUR:'چکن کالی مرچ چاول',
equipment:['induction','smart pot'],nightPrep:false,
ingredients:[
  {emoji:'🍗',name:'Chicken (boneless, diced)',nameTA:'சிக்கன்',nameUR:'مرغی',qty:200,unit:'g'},
  {emoji:'🍚',name:'Cooked rice',nameTA:'சாதம்',nameUR:'چاول',qty:1.5,unit:'cups'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:1,unit:'medium'},
  {emoji:'⚫',name:'Black pepper (coarsely ground)',nameTA:'மிளகு',nameUR:'کالی مرچ',qty:1.5,unit:'tsp'},
  {emoji:'🌿',name:'Curry leaves',nameTA:'கறிவேப்பிலை',nameUR:'کڑی پتہ',qty:8,unit:'leaves'},
  {emoji:'🫙',name:'Ginger-garlic paste',nameTA:'இஞ்சி பூண்டு',nameUR:'ادرک لہسن',qty:1,unit:'tsp'},
  {emoji:'🧂',name:'Salt + garam masala',nameTA:'உப்பு கரம் மசாலா',nameUR:'نمک گرم مسالا',qty:0.5,unit:'tsp each'},
],
steps:[
  {text:'Press **Sauté** → **Start** on Smart Pot. Add oil + curry leaves + onion. Fry until golden brown (4 min).',timer:240},
  {text:'Add ginger-garlic paste. Stir 30 sec. Add chicken + black pepper + garam masala + salt. Stir well.',timer:60},
  {text:'Press **Cancel**. Close lid. Press **Meat** → 10 min → **Start**. Quick release.',timer:600},
  {text:'Open. Press **Sauté** → **Start**. Toss chicken in remaining juices until slightly dry and coated. Press **Cancel**.',timer:120},
  {text:'Serve pepper chicken masala over rice. Mix and eat.',timer:0},
],
tip:'This is a Chennai-style dry pepper chicken — the heat comes entirely from black pepper, not chili. Use freshly ground coarse pepper for best results. The curry leaves are essential.',
video:'chicken pepper rice recipe South Indian style',
},

{id:'lm13',type:'lunch',effort:'medium',time:25,protein:22,calories:410,emoji:'🍳',
name:'Keema Fried Rice',nameTA:'கீமா வறுத்த சாதம்',nameUR:'قیمہ فرائیڈ رائس',
equipment:['induction'],nightPrep:true,
ingredients:[
  {emoji:'🍗',name:'Minced chicken (keema)',nameTA:'சிக்கன் கீமா',nameUR:'چکن قیمہ',qty:150,unit:'g'},
  {emoji:'🍚',name:'Cooked rice (day-old)',nameTA:'சாதம்',nameUR:'چاول',qty:1.5,unit:'cups'},
  {emoji:'🥚',name:'Egg',nameTA:'முட்டை',nameUR:'انڈا',qty:1,unit:'nos'},
  {emoji:'🧅',name:'Onion + spring onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:0.5,unit:'each'},
  {emoji:'🫙',name:'Soy sauce + ginger-garlic paste',nameTA:'சோயா சாஸ்',nameUR:'سویا ساس ادرک لہسن',qty:1,unit:'tsp each'},
  {emoji:'🔴',name:'Chili powder + black pepper',nameTA:'மிளகாய் மிளகு',nameUR:'مرچ کالی مرچ',qty:0.5,unit:'tsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.5,unit:'tsp'},
],
steps:[
  {text:'Heat flat pan on V-Guard 1600W (very hot). Add 1 tsp oil. Fry keema with ginger-garlic paste + chili + pepper + salt until cooked through (5–6 min). Break all lumps. Set aside.',timer:360},
  {text:'Same pan: add 0.5 tsp oil. Crack egg + scramble quickly. Remove.',timer:60},
  {text:'Add onion. Stir-fry 1 min on high. Add rice. Toss on high heat.',timer:60},
  {text:'Add soy sauce + cooked keema + scrambled egg. Toss together 2 min. Serve hot.',timer:120},
],
tip:'Keema can be cooked and refrigerated overnight — makes morning assembly faster. High heat is critical for fried rice. Add a few drops of sesame oil at the end for authentic flavor.',
video:'keema fried rice recipe chicken minced',
},

{id:'lm14',type:'lunch',effort:'medium',time:20,protein:22,calories:380,emoji:'🍜',
name:'Chicken Noodles (Indo-Chinese)',nameTA:'சிக்கன் நூடுல்ஸ்',nameUR:'چکن نوڈلز',
equipment:['induction','smart pot'],nightPrep:false,
ingredients:[
  {emoji:'🍜',name:'Egg noodles (or Maggi)',nameTA:'நூடுல்ஸ்',nameUR:'نوڈلز',qty:100,unit:'g'},
  {emoji:'🍗',name:'Chicken (shredded, cooked)',nameTA:'சிக்கன்',nameUR:'مرغی',qty:100,unit:'g'},
  {emoji:'🥕',name:'Carrot + cabbage (shredded)',nameTA:'கேரட் முட்டைக்கோஸ்',nameUR:'گاجر پت گوبھی',qty:0.25,unit:'cup each'},
  {emoji:'🧅',name:'Onion + spring onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:0.5,unit:'each'},
  {emoji:'🫙',name:'Soy sauce + chili sauce',nameTA:'சோயா சாஸ் மிளகாய் சாஸ்',nameUR:'سویا ساس مرچ ساس',qty:1,unit:'tsp each'},
  {emoji:'🧂',name:'Salt + black pepper',nameTA:'உப்பு மிளகு',nameUR:'نمک کالی مرچ',qty:0.5,unit:'tsp each'},
],
steps:[
  {text:'Boil noodles in Smart Pot (Steam 5 min or boil in kettle 3 min with water). Drain. Rinse cold water. Toss 1 tsp oil to prevent sticking.',timer:300},
  {text:'Heat flat pan on V-Guard 1600W (smoking hot). Add 1.5 tsp oil. Stir-fry onion + carrot + cabbage 2 min on high. Veggies should stay slightly crunchy.',timer:120},
  {text:'Add shredded chicken + soy sauce + chili sauce + salt + pepper. Toss 1 min.',timer:60},
  {text:'Add drained noodles. Toss everything together on high heat 2 min. Add spring onion on top. Serve immediately.',timer:120},
],
tip:'Use pre-cooked shredded chicken from previous dinner (leftover). High heat and fast tossing gives the "wok hei" restaurant flavor. Do not cover with lid — steam makes noodles soggy.',
video:'chicken noodles Indo Chinese recipe',
},

{id:'lm15',type:'lunch',effort:'medium',time:15,protein:16,calories:360,emoji:'🍜',
name:'Egg Fried Noodles',nameTA:'முட்டை வறுத்த நூடுல்ஸ்',nameUR:'انڈا فرائیڈ نوڈلز',
equipment:['induction','smart pot'],nightPrep:false,
ingredients:[
  {emoji:'🍜',name:'Instant noodles (Maggi/Sunfeast Yippee)',nameTA:'நூடுல்ஸ்',nameUR:'نوڈلز',qty:100,unit:'g'},
  {emoji:'🥚',name:'Eggs',nameTA:'முட்டை',nameUR:'انڈا',qty:2,unit:'nos'},
  {emoji:'🥕',name:'Carrot + cabbage (shredded)',nameTA:'கேரட் முட்டைக்கோஸ்',nameUR:'گاجر گوبھی',qty:0.25,unit:'cup each'},
  {emoji:'🧅',name:'Onion + spring onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:0.5,unit:'each'},
  {emoji:'🫙',name:'Soy sauce',nameTA:'சோயா சாஸ்',nameUR:'سویا ساس',qty:1.5,unit:'tsp'},
  {emoji:'🧂',name:'Salt + black pepper',nameTA:'உப்பு மிளகு',nameUR:'نمک کالی مرچ',qty:0.5,unit:'tsp each'},
],
steps:[
  {text:'Boil noodles in kettle (knob → **II (High)**, cook 3 min). Drain, rinse cold, toss with 1 tsp oil.',timer:180},
  {text:'Heat flat pan on V-Guard 1600W. Add 1 tsp oil. Scramble eggs quickly in large pieces. Remove.',timer:60},
  {text:'Same pan: add 0.5 tsp oil. Add onion + carrot + cabbage. Stir-fry 2 min on high — keep crunchy.',timer:120},
  {text:'Add noodles + soy sauce + pepper + salt. Toss 1 min. Add eggs back. Toss together. Top with spring onion.',timer:60},
],
tip:'Do NOT use the tastemaker sachet from Maggi — just plain boiled noodles. The soy sauce + pepper is the seasoning. Keep veggies crunchy by not overcooking on high heat.',
video:'egg fried noodles recipe quick easy',
},

{id:'lm16',type:'lunch',effort:'medium',time:30,protein:14,calories:380,emoji:'🫘',
name:'Bisi Bele Bath',nameTA:'பிசி பேளே பாத்',nameUR:'بیسی بیلے باتھ',
equipment:['smart pot'],nightPrep:false,
ingredients:[
  {emoji:'🍚',name:'Rice',nameTA:'அரிசி',nameUR:'چاول',qty:0.5,unit:'cup'},
  {emoji:'🫘',name:'Toor dal',nameTA:'துவரம் பருப்பு',nameUR:'ارہر دال',qty:0.25,unit:'cup'},
  {emoji:'🥕',name:'Mixed vegetables (carrot, peas, beans)',nameTA:'கலந்த காய்கறி',nameUR:'ملی سبزی',qty:0.5,unit:'cup'},
  {emoji:'🟡',name:'Tamarind paste',nameTA:'புளி',nameUR:'تمر ہندی',qty:1,unit:'tsp'},
  {emoji:'🫙',name:'Sambar powder',nameTA:'சாம்பார் பொடி',nameUR:'سمبر پاؤڈر',qty:1.5,unit:'tsp'},
  {emoji:'🧈',name:'Ghee',nameTA:'நெய்',nameUR:'گھی',qty:1.5,unit:'tsp'},
  {emoji:'🧂',name:'Salt + jaggery',nameTA:'உப்பு வெல்லம்',nameUR:'نمک گڑ',qty:0.5,unit:'tsp each'},
],
steps:[
  {text:'Wash rice + dal. Press **Sauté** → **Start** on Smart Pot. Add ghee + mustard seeds + curry leaves (optional). Press **Cancel** after 30 sec.',timer:30},
  {text:'Add rice + dal + vegetables + tamarind + sambar powder + jaggery + salt + 3 cups water. Stir.',timer:0},
  {text:'Close lid. Press **Bean** → 15 min → **Start**.',timer:900},
  {text:'Natural release 5 min. Open lid. Stir vigorously — bisi bele bath should be porridge-like and mushy. Add ghee on top. Serve hot.',timer:300},
],
tip:'Bisi bele bath is a Karnataka classic — literally "hot lentil rice bath". Should be very mushy (not separate grains) and slightly tangy-sweet. Add extra ghee for richness. Serve with papad.',
video:'bisi bele bath recipe Karnataka style pressure cooker',
},

{id:'lm17',type:'lunch',effort:'medium',time:35,protein:30,calories:460,emoji:'🍖',
name:'Mutton Chops + Rice',nameTA:'ஆட்டு சாப்ஸ் சாதம்',nameUR:'بکرے کے چاپس چاول',
equipment:['smart pot'],nightPrep:false,
ingredients:[
  {emoji:'🍖',name:'Mutton chops (bone-in)',nameTA:'ஆட்டு இறைச்சி',nameUR:'بکری کا گوشت',qty:200,unit:'g'},
  {emoji:'🍚',name:'Cooked rice',nameTA:'சாதம்',nameUR:'چاول',qty:1.5,unit:'cups'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:1,unit:'medium'},
  {emoji:'🍅',name:'Tomato',nameTA:'தக்காளி',nameUR:'ٹماٹر',qty:1,unit:'medium'},
  {emoji:'🫙',name:'Ginger-garlic paste',nameTA:'இஞ்சி பூண்டு',nameUR:'ادرک لہسن',qty:1.5,unit:'tsp'},
  {emoji:'🔴',name:'Chili + coriander + garam masala',nameTA:'மிளகாய் கொத்தமல்லி மசாலா',nameUR:'مرچ دھنیا گرم مسالا',qty:1,unit:'tsp each'},
  {emoji:'🧂',name:'Salt + coriander leaves',nameTA:'உப்பு',nameUR:'نمک دھنیا',qty:0.75,unit:'tsp'},
],
steps:[
  {text:'Press **Sauté** → **Start** on Smart Pot. Add 2 tsp oil. Fry onion until golden brown (4 min).',timer:240},
  {text:'Add ginger-garlic paste (1 min). Add tomato + all spices + salt. Cook 2 min until oil separates. Press **Cancel**.',timer:180},
  {text:'Add mutton chops + 100ml water. Close lid. Press **Meat** → 20 min → **Start**.',timer:1200},
  {text:'Natural release 10 min. Open. Mutton should be tender — meat falls off bone when pulled. Garnish coriander.',timer:600},
  {text:'Serve masala mutton over plain rice.',timer:0},
],
tip:'Mutton takes longer than chicken — 20 min in pressure cooker gives fork-tender results. Buy fresh mutton from halal butcher (₹400–500/500g). The bone marrow adds incredible richness to the gravy.',
video:'mutton chops recipe pressure cooker spicy',
},

{id:'lm18',type:'lunch',effort:'medium',time:30,protein:12,calories:350,emoji:'🫘',
name:'Dal Makhani + Chapati',nameTA:'தால் மக்கனி சப்பாத்தி',nameUR:'دال مکھنی چپاتی',
equipment:['smart pot','flat pan'],nightPrep:true,
ingredients:[
  {emoji:'🫘',name:'Whole black lentils (urad dal)',nameTA:'முழு உளுந்து',nameUR:'کالی اڑد دال',qty:0.5,unit:'cup'},
  {emoji:'🫘',name:'Kidney beans (rajma, canned OK)',nameTA:'ராஜ்மா',nameUR:'راجما',qty:2,unit:'tbsp'},
  {emoji:'🍅',name:'Tomato puree',nameTA:'தக்காளி சாறு',nameUR:'ٹماٹر پیورے',qty:3,unit:'tbsp'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:1,unit:'small'},
  {emoji:'🧈',name:'Butter + cream (or just butter)',nameTA:'வெண்ணெய்',nameUR:'مکھن',qty:1.5,unit:'tbsp'},
  {emoji:'🔴',name:'Chili + cumin + garam masala',nameTA:'மிளகாய் சீரகம்',nameUR:'مرچ زیرہ گرم مسالا',qty:0.5,unit:'tsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.75,unit:'tsp'},
  {emoji:'🌾',name:'Atta + water (for 2 chapatis)',nameTA:'கோதுமை மாவு',nameUR:'آٹا',qty:0.5,unit:'cup'},
],
steps:[
  {text:'Night before: soak urad dal in water 8 hours. In Smart Pot: add soaked dal + rajma + 2 cups water. Press **Bean** → 20 min → **Start**. Natural release. Refrigerate dal overnight.',timer:1200},
  {text:'Morning assembly: Press **Sauté** → **Start**. Add butter + onion. Fry 3 min. Add tomato puree + spices + salt. Cook 2 min.',timer:300},
  {text:'Add cooked dal. Simmer on **Sauté** 5 min, stirring. Add butter at end. Rich, creamy dark gravy. Press **Cancel**.',timer:300},
  {text:'Chapati: knead atta + water → flat dough. Roll 2 chapatis thin. Cook on flat pan (V-Guard 1600W) 1 min each side. Apply ghee.',timer:120},
  {text:'Serve dal makhani with 2 warm chapatis.',timer:0},
],
tip:'Overnight soaking is essential for whole urad dal. The longer it simmers after pressure cooking, the creamier it gets. Restaurant dal makhani simmers for hours — 10 extra min on sauté helps a lot.',
video:'dal makhani recipe dhaba style home',
},

{id:'lm19',type:'lunch',effort:'medium',time:25,protein:26,calories:410,emoji:'🍗',
name:'Chicken Masala + Rice',nameTA:'சிக்கன் மசாலா சாதம்',nameUR:'چکن مسالا چاول',
equipment:['smart pot'],nightPrep:false,
ingredients:[
  {emoji:'🍗',name:'Chicken (bone-in pieces)',nameTA:'சிக்கன்',nameUR:'مرغی',qty:250,unit:'g'},
  {emoji:'🍚',name:'Cooked rice',nameTA:'சாதம்',nameUR:'چاول',qty:1.5,unit:'cups'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:1,unit:'large'},
  {emoji:'🍅',name:'Tomato',nameTA:'தக்காளி',nameUR:'ٹماٹر',qty:1,unit:'medium'},
  {emoji:'🫙',name:'Aachi Chicken Masala powder',nameTA:'சிக்கன் மசாலா',nameUR:'چکن مسالا',qty:1.5,unit:'tsp'},
  {emoji:'🫙',name:'Ginger-garlic paste',nameTA:'இஞ்சி பூண்டு',nameUR:'ادرک لہسن',qty:1,unit:'tsp'},
  {emoji:'🧂',name:'Salt + coriander leaves',nameTA:'உப்பு',nameUR:'نمک دھنیا',qty:0.75,unit:'tsp'},
],
steps:[
  {text:'Press **Sauté** → **Start** on Smart Pot. Add 2 tsp oil. Fry onion until golden brown (4–5 min).',timer:300},
  {text:'Add ginger-garlic paste. Stir 1 min. Add chopped tomato + Aachi chicken masala + salt. Cook 2 min. Press **Cancel**.',timer:180},
  {text:'Add chicken pieces. Toss to coat. Add 75ml water. Close lid. Press **Meat** → 12 min → **Start**.',timer:720},
  {text:'Natural release 5 min. Open. If gravy is thin, press **Sauté**, boil 3 min uncovered. Garnish coriander.',timer:300},
  {text:'Serve over plain rice.',timer:0},
],
tip:'Aachi Chicken Masala (₹15/50g pack) is the most convenient spice blend for a Chennai bachelor — authentic flavor with zero guesswork. Bone-in chicken gives better gravy than boneless.',
video:'chicken masala recipe South Indian pressure cooker',
},

{id:'lm20',type:'lunch',effort:'medium',time:25,protein:16,calories:390,emoji:'🧀',
name:'Paneer Butter Masala + Chapati',nameTA:'பன்னீர் வெண்ணெய் மசாலா',nameUR:'پنیر مکھن مسالا چپاتی',
equipment:['smart pot','flat pan'],nightPrep:false,
ingredients:[
  {emoji:'🧀',name:'Paneer (cubed)',nameTA:'பன்னீர்',nameUR:'پنیر',qty:150,unit:'g'},
  {emoji:'🍅',name:'Tomato',nameTA:'தக்காளி',nameUR:'ٹماٹر',qty:2,unit:'medium'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:1,unit:'medium'},
  {emoji:'🧈',name:'Butter',nameTA:'வெண்ணெய்',nameUR:'مکھن',qty:1.5,unit:'tbsp'},
  {emoji:'🫙',name:'Ginger-garlic paste + chili powder + garam masala',nameTA:'இஞ்சி பூண்டு மிளகாய்',nameUR:'ادرک لہسن مرچ مسالا',qty:0.5,unit:'tsp each'},
  {emoji:'🥛',name:'Fresh cream or full cream milk',nameTA:'கிரீம் பால்',nameUR:'کریم دودھ',qty:2,unit:'tbsp'},
  {emoji:'🌾',name:'Atta (for 2 chapatis)',nameTA:'கோதுமை மாவு',nameUR:'آٹا',qty:0.5,unit:'cup'},
  {emoji:'🧂',name:'Salt + coriander',nameTA:'உப்பு',nameUR:'نمک دھنیا',qty:0.5,unit:'tsp'},
],
steps:[
  {text:'Blend onion + tomato in NutriPro blender to smooth puree. Set aside.',timer:0},
  {text:'Press **Sauté** → **Start** on Smart Pot. Add butter. Add puree + ginger-garlic + chili + garam masala + salt. Cook 5 min stirring until oil separates and paste thickens. Press **Cancel**.',timer:300},
  {text:'Add paneer cubes + 50ml water. Close lid. Press **Pressure Cook** → 4 min → **Start**. Quick release.',timer:240},
  {text:'Open. Add cream. Stir gently. Garnish coriander.',timer:0},
  {text:'Serve with 2 fresh chapatis made on flat pan (V-Guard 1600W, 1 min each side with ghee).',timer:120},
],
tip:'Do not overcook paneer — it becomes rubbery. 4 min in pressure cooker is enough. For restaurant-style color, add 0.5 tsp Kashmiri chili powder. Fresh Aavin paneer (₹80/100g) is available in Chennai.',
video:'paneer butter masala recipe restaurant style',
},

"""

marker = '];\n\nwindow.__PANTRY__'
pos = content.find(marker)
if pos == -1:
    print('ERROR: marker not found')
else:
    content = content[:pos] + NEW + content[pos:]
    with open(r'C:\Users\Syed Asrar\bachelor-meal-plan\meals.js', 'w', encoding='utf-8') as f:
        f.write(content)
    print('Lunch medium lm9-lm20 inserted (12 recipes)')
