with open(r'C:\Users\Syed Asrar\bachelor-meal-plan\meals.js', 'r', encoding='utf-8') as f:
    content = f.read()

NEW = r"""
{id:'ls7',type:'lunch',effort:'simple',time:5,protein:7,calories:260,emoji:'🍚',
name:'Thayir Sadam (Temple Curd Rice)',nameTA:'தயிர் சாதம்',nameUR:'دہی چاول',
equipment:[],nightPrep:false,
ingredients:[
  {emoji:'🍚',name:'Cooked rice',nameTA:'சாதம்',nameUR:'چاول',qty:1.5,unit:'cups'},
  {emoji:'🍶',name:'Fresh curd',nameTA:'தயிர்',nameUR:'دہی',qty:200,unit:'ml'},
  {emoji:'🥛',name:'Milk (cold)',nameTA:'பால்',nameUR:'دودھ',qty:2,unit:'tbsp'},
  {emoji:'🌶️',name:'Green chili (minced)',nameTA:'பச்சை மிளகாய்',nameUR:'ہری مرچ',qty:0.5,unit:'nos'},
  {emoji:'🌿',name:'Curry leaves + mustard (for tadka)',nameTA:'கறிவேப்பிலை கடுகு',nameUR:'کڑی پتہ رائی',qty:4,unit:'leaves + 0.25 tsp'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.5,unit:'tsp'},
  {emoji:'🍇',name:'Pomegranate seeds (optional)',nameTA:'மாதுளை',nameUR:'انار',qty:1,unit:'tbsp'},
],
steps:[
  {text:'Mash warm cooked rice slightly. Mix curd + milk + salt into rice. Curd rice should be creamy, not dry. Add cold milk if too thick.',timer:0},
  {text:'Optional tadka: heat 1 tsp oil in small pan on V-Guard 1000W. Add mustard seeds (let splutter) + curry leaves + minced green chili. Pour over curd rice.',timer:60},
  {text:'Top with pomegranate seeds if available. Serve at room temperature or chilled. Pairs with mango pickle (avakkai).',timer:0},
],
tip:'Temple-style thayir sadam uses soft rice, whole milk, and is eaten at room temp — slightly different from quick curd rice. Cold milk makes it creamy. Pack for lunch in steel box.',
video:'thayir sadam recipe temple style curd rice',
},

{id:'ls8',type:'lunch',effort:'simple',time:10,protein:6,calories:270,emoji:'🍋',
name:'Lemon Rice (Chitranna)',nameTA:'எலுமிச்சை சாதம்',nameUR:'لیموں چاول',
equipment:['induction'],nightPrep:false,
ingredients:[
  {emoji:'🍚',name:'Cooked rice (cooled)',nameTA:'சாதம்',nameUR:'چاول',qty:1.5,unit:'cups'},
  {emoji:'🍋',name:'Lemon',nameTA:'எலுமிச்சை',nameUR:'لیموں',qty:1,unit:'nos'},
  {emoji:'🌰',name:'Roasted peanuts',nameTA:'வேர்க்கடலை',nameUR:'مونگ پھلی',qty:2,unit:'tbsp'},
  {emoji:'🌶️',name:'Dried red chili',nameTA:'வரண்ட மிளகாய்',nameUR:'سوکھی مرچ',qty:1,unit:'nos'},
  {emoji:'🟡',name:'Turmeric',nameTA:'மஞ்சள்',nameUR:'ہلدی',qty:0.25,unit:'tsp'},
  {emoji:'🌿',name:'Curry leaves + mustard seeds + urad dal',nameTA:'கறிவேப்பிலை கடுகு',nameUR:'کڑی پتہ رائی',qty:4,unit:'leaves + 0.25 tsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.75,unit:'tsp'},
],
steps:[
  {text:'Ensure rice is cooled or at room temperature. Spread out if fresh — hot clumpy rice works poorly.',timer:0},
  {text:'Heat flat pan on V-Guard 1200W. Add 1.5 tsp oil. Add mustard + urad dal + dried red chili + curry leaves + peanuts. Fry 30 sec until mustard splutters.',timer:30},
  {text:'Add turmeric + salt to the oil. Turn off heat. Add this hot tempering directly over spread rice.',timer:0},
  {text:'Squeeze entire lemon over rice. Toss gently until all rice is coated yellow. Taste and adjust lemon/salt.',timer:0},
],
tip:'Rice must be cooled or at room temp — never use hot rice for lemon rice as it becomes mushy. Excellent packed lunch as it tastes better after 1–2 hours. Makes enough for tiffin box.',
video:'lemon rice recipe chitranna south indian',
},

{id:'ls9',type:'lunch',effort:'simple',time:10,protein:5,calories:280,emoji:'🟤',
name:'Puliyodarai (Tamarind Rice)',nameTA:'புளியோதரை',nameUR:'تمر ہندی چاول',
equipment:['induction'],nightPrep:false,
ingredients:[
  {emoji:'🍚',name:'Cooked rice',nameTA:'சாதம்',nameUR:'چاول',qty:1.5,unit:'cups'},
  {emoji:'🟡',name:'Tamarind paste (ready-made)',nameTA:'புளி',nameUR:'تمر ہندی پیسٹ',qty:1,unit:'tbsp'},
  {emoji:'🌰',name:'Roasted peanuts',nameTA:'வேர்க்கடலை',nameUR:'مونگ پھلی',qty:2,unit:'tbsp'},
  {emoji:'🌿',name:'Curry leaves + mustard + chana dal',nameTA:'கறிவேப்பிலை கடுகு',nameUR:'کڑی پتہ رائی',qty:4,unit:'leaves + 0.25 tsp each'},
  {emoji:'🔴',name:'Sambar powder + chili powder',nameTA:'சாம்பார் மிளகாய் பொடி',nameUR:'سمبر مرچ پاؤڈر',qty:0.5,unit:'tsp each'},
  {emoji:'🧂',name:'Salt + jaggery (small piece)',nameTA:'உப்பு வெல்லம்',nameUR:'نمک گڑ',qty:0.5,unit:'tsp + small piece'},
],
steps:[
  {text:'Mix tamarind paste + sambar powder + chili powder + jaggery + salt + 2 tbsp water in small bowl to make puliyodarai paste.',timer:0},
  {text:'Heat flat pan on V-Guard 1200W. Add 2 tsp oil. Add mustard + chana dal + curry leaves + peanuts. Fry 30 sec.',timer:30},
  {text:'Add the tamarind paste mixture. Cook on 1000W for 2–3 min until fragrant and oil separates.',timer:180},
  {text:'Add cooked rice. Toss well to coat evenly. Taste and adjust sourness/salt/heat.',timer:0},
],
tip:'Store-bought tamarind paste (Aachi brand) works perfectly — no soaking needed. Puliyodarai travels well in lunchbox (no spoiling). Temple prasadam uses a special black pepper version.',
video:'puliyodarai recipe tamarind rice south indian',
},

{id:'ls10',type:'lunch',effort:'simple',time:10,protein:5,calories:260,emoji:'🥥',
name:'Coconut Rice (Thengai Sadam)',nameTA:'தேங்காய் சாதம்',nameUR:'ناریل چاول',
equipment:['induction'],nightPrep:false,
ingredients:[
  {emoji:'🍚',name:'Cooked rice',nameTA:'சாதம்',nameUR:'چاول',qty:1.5,unit:'cups'},
  {emoji:'🥥',name:'Fresh grated coconut',nameTA:'தேங்காய் துருவல்',nameUR:'ناریل',qty:4,unit:'tbsp'},
  {emoji:'🌰',name:'Roasted peanuts + cashews',nameTA:'வேர்க்கடலை முந்திரி',nameUR:'مونگ پھلی کاجو',qty:1,unit:'tbsp each'},
  {emoji:'🌶️',name:'Dried red chili',nameTA:'வரண்ட மிளகாய்',nameUR:'سوکھی لال مرچ',qty:2,unit:'nos'},
  {emoji:'🌿',name:'Curry leaves + mustard + urad dal',nameTA:'கறிவேப்பிலை கடுகு',nameUR:'کڑی پتہ',qty:4,unit:'leaves + 0.25 tsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.5,unit:'tsp'},
],
steps:[
  {text:'Heat flat pan on V-Guard 1200W. Add 1 tsp oil. Add mustard + urad dal + red chili + curry leaves + cashews. Fry 30 sec.',timer:30},
  {text:'Add grated coconut + peanuts + salt. Stir on 1000W for 1 min until lightly toasted.',timer:60},
  {text:'Add cooked rice. Toss gently. Mix until all grains are coated with coconut and tempered spices.',timer:0},
  {text:'Serve with pickle or pappad on side.',timer:0},
],
tip:'Fresh coconut is ideal but frozen grated coconut also works. Coconut rice is a classic Tamil Nadu lunch — slightly sweet, nutty, and fragrant. Best eaten the same day.',
video:'thengai sadam recipe coconut rice south indian',
},

{id:'ls11',type:'lunch',effort:'simple',time:8,protein:9,calories:290,emoji:'🥜',
name:'Peanut Rice (Verkadalai Sadam)',nameTA:'வேர்க்கடலை சாதம்',nameUR:'مونگ پھلی چاول',
equipment:['induction'],nightPrep:false,
ingredients:[
  {emoji:'🍚',name:'Cooked rice',nameTA:'சாதம்',nameUR:'چاول',qty:1.5,unit:'cups'},
  {emoji:'🌰',name:'Roasted peanuts (salted)',nameTA:'வேர்க்கடலை',nameUR:'مونگ پھلی',qty:3,unit:'tbsp'},
  {emoji:'🌶️',name:'Dried red chili',nameTA:'வரண்ட மிளகாய்',nameUR:'سوکھی مرچ',qty:1,unit:'nos'},
  {emoji:'🌿',name:'Curry leaves + mustard + chana dal',nameTA:'கறிவேப்பிலை கடுகு',nameUR:'کڑی پتہ',qty:4,unit:'leaves + 0.25 tsp each'},
  {emoji:'🍋',name:'Lemon juice',nameTA:'எலுமிச்சை',nameUR:'لیموں',qty:1,unit:'tsp'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.5,unit:'tsp'},
],
steps:[
  {text:'Heat flat pan on V-Guard 1200W. Add 1 tsp oil. Add mustard + chana dal + red chili + curry leaves. Fry 30 sec until mustard splutters.',timer:30},
  {text:'Add peanuts + salt. Toss 30 sec. Turn off heat.',timer:30},
  {text:'Add cooked rice. Squeeze lemon. Toss well. Serve with curd or pickle.',timer:0},
],
tip:'If peanuts are raw, dry roast them in the pan first for 3–4 min on 1000W before tempering. Salted roasted peanuts (buy pack from store) save time. High protein compared to other rice dishes.',
video:'peanut rice recipe verkadalai sadam',
},

{id:'ls12',type:'lunch',effort:'simple',time:12,protein:6,calories:260,emoji:'🍅',
name:'Tomato Rice (Simple)',nameTA:'தக்காளி சாதம்',nameUR:'ٹماٹر چاول',
equipment:['induction'],nightPrep:false,
ingredients:[
  {emoji:'🍚',name:'Cooked rice',nameTA:'சாதம்',nameUR:'چاول',qty:1.5,unit:'cups'},
  {emoji:'🍅',name:'Tomato',nameTA:'தக்காளி',nameUR:'ٹماٹر',qty:2,unit:'nos'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:0.5,unit:'small'},
  {emoji:'🌿',name:'Curry leaves + mustard',nameTA:'கறிவேப்பிலை கடுகு',nameUR:'کڑی پتہ',qty:4,unit:'leaves + 0.25 tsp'},
  {emoji:'🔴',name:'Sambar powder + chili powder',nameTA:'சாம்பார் மிளகாய்',nameUR:'سمبر مرچ',qty:0.5,unit:'tsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.75,unit:'tsp'},
],
steps:[
  {text:'Heat flat pan on V-Guard 1200W. Add 1 tsp oil. Add mustard + curry leaves + sliced onion. Sauté 2 min.',timer:120},
  {text:'Add chopped tomatoes + sambar powder + chili powder + salt. Cook on 1200W until tomatoes break down into thick paste (4–5 min). Press with spoon to help.',timer:300},
  {text:'Add cooked rice. Toss gently. Mix well until all rice turns red-orange. Serve hot.',timer:0},
],
tip:'Lunch version is simpler than the dinner ds15 version — just tomato base, no extra vegetables. Add a fried egg or boiled egg on side for protein.',
video:'tomato rice quick lunch recipe',
},

{id:'ls13',type:'lunch',effort:'simple',time:20,protein:12,calories:320,emoji:'🫘',
name:'Moong Dal Khichdi',nameTA:'பாசிப்பருப்பு கிச்சடி',nameUR:'موٹ دال کھچڑی',
equipment:['smart pot'],nightPrep:false,
ingredients:[
  {emoji:'🍚',name:'Sona masoori rice',nameTA:'அரிசி',nameUR:'چاول',qty:0.5,unit:'cup'},
  {emoji:'🫘',name:'Moong dal (split yellow)',nameTA:'பாசிப்பருப்பு',nameUR:'موٹ دال',qty:0.25,unit:'cup'},
  {emoji:'🟡',name:'Turmeric',nameTA:'மஞ்சள்',nameUR:'ہلدی',qty:0.25,unit:'tsp'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:0.5,unit:'small'},
  {emoji:'🌶️',name:'Green chili',nameTA:'பச்சை மிளகாய்',nameUR:'ہری مرچ',qty:1,unit:'nos'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمக',qty:0.75,unit:'tsp'},
  {emoji:'🧈',name:'Ghee',nameTA:'நெய்',nameUR:'گھی',qty:1,unit:'tsp'},
],
steps:[
  {text:'Wash rice + moong dal together. Press **Sauté** → **Start** on Smart Pot. Add ghee + cumin seeds (optional) + onion + green chili. Sauté 1 min. Press **Cancel**.',timer:60},
  {text:'Add washed rice + dal + turmeric + salt + 2.5 cups water. Stir.',timer:0},
  {text:'Press **Bean** → adjust to 8 min → **Start**.',timer:480},
  {text:'Natural release 5 min. Open lid. Stir vigorously — khichdi should be soft, porridge-like. Add ghee on top.',timer:300},
],
tip:'Khichdi is the simplest complete meal — rice + protein in one pot. The consistency should be soft and mushy (not separate grains). Serve with pickle and papad. Excellent for digestion.',
video:'moong dal khichdi recipe one pot',
},

{id:'ls14',type:'lunch',effort:'simple',time:12,protein:15,calories:340,emoji:'🍳',
name:'Egg Fried Rice (Simple)',nameTA:'முட்டை வறுத்த சாதம்',nameUR:'انڈا فرائیڈ رائس',
equipment:['induction'],nightPrep:false,
ingredients:[
  {emoji:'🍚',name:'Cooked rice (day-old is best)',nameTA:'சாதம்',nameUR:'چاول',qty:1.5,unit:'cups'},
  {emoji:'🥚',name:'Eggs',nameTA:'முட்டை',nameUR:'انڈا',qty:2,unit:'nos'},
  {emoji:'🧅',name:'Onion + spring onion (if available)',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:0.5,unit:'each'},
  {emoji:'🫙',name:'Soy sauce',nameTA:'சோயா சாஸ்',nameUR:'سویا ساس',qty:1,unit:'tsp'},
  {emoji:'🧂',name:'Salt + black pepper',nameTA:'உப்பு மிளகு',nameUR:'نمک کالی مرچ',qty:0.5,unit:'tsp each'},
],
steps:[
  {text:'Beat eggs with salt. Push rice grains apart with fingers (day-old rice separates better than fresh).',timer:0},
  {text:'Heat flat pan on V-Guard 1600W (very hot). Add 1.5 tsp oil. Pour eggs in — scramble quickly in large pieces. Remove and set aside.',timer:60},
  {text:'Same hot pan: add 0.5 tsp oil + diced onion. Stir-fry 1 min on high heat.',timer:60},
  {text:'Add rice. Toss quickly on high heat. Add soy sauce + black pepper. Toss 2 min. Add scrambled eggs back. Mix. Serve immediately.',timer:120},
],
tip:'High heat is essential for fried rice — a lukewarm pan makes sticky, steamed rice, not fried rice. Day-old refrigerator rice is best. Add a drop of sesame oil at the end for flavor.',
video:'egg fried rice simple quick recipe',
},

{id:'ls15',type:'lunch',effort:'simple',time:15,protein:8,calories:300,emoji:'🍲',
name:'Sambar Rice (One Pot)',nameTA:'சாம்பார் சாதம்',nameUR:'سمبر چاول',
equipment:['smart pot'],nightPrep:false,
ingredients:[
  {emoji:'🍚',name:'Rice',nameTA:'அரிசி',nameUR:'چاول',qty:0.75,unit:'cup'},
  {emoji:'🫘',name:'Toor dal',nameTA:'துவரம் பருப்பு',nameUR:'ارہر دال',qty:2,unit:'tbsp'},
  {emoji:'🍅',name:'Tomato',nameTA:'தக்காளி',nameUR:'ٹماٹر',qty:1,unit:'nos'},
  {emoji:'🍆',name:'Brinjal (optional)',nameTA:'கத்திரிக்காய்',nameUR:'بینگن',qty:1,unit:'small'},
  {emoji:'🫙',name:'Aachi Sambar powder',nameTA:'சாம்பார் பொடி',nameUR:'سمبر پاؤڈر',qty:1,unit:'tsp'},
  {emoji:'🟡',name:'Tamarind paste + turmeric',nameTA:'புளி மஞ்சள்',nameUR:'تمر ہندی ہلدی',qty:0.5,unit:'tsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.75,unit:'tsp'},
],
steps:[
  {text:'Wash rice + dal together. Add to Smart Pot with tomato + brinjal + sambar powder + tamarind paste + turmeric + salt + 2.5 cups water.',timer:0},
  {text:'Press **Bean** → 12 min → **Start**.',timer:720},
  {text:'Natural release 5 min. Open lid. Stir well — if too thick, add 0.25 cup hot water.',timer:300},
  {text:'Quick tadka: heat 1 tsp oil in pan, add mustard + curry leaves, pour over sambar rice. Serve.',timer:30},
],
tip:'This is sambar and rice cooked together — like a thick sambar with rice. Very filling and nutritious. Add any vegetable available (carrot, peas, drumstick). Classic Tamil lunch.',
video:'sambar sadam recipe one pot south indian',
},

{id:'ls16',type:'lunch',effort:'simple',time:8,protein:6,calories:220,emoji:'🫗',
name:'Rasam Rice + Papad',nameTA:'ரசம் சாதம் அப்பளம்',nameUR:'رسم چاول پاپڑ',
equipment:['kettle'],nightPrep:false,
ingredients:[
  {emoji:'🍚',name:'Cooked rice',nameTA:'சாதம்',nameUR:'چاول',qty:1.5,unit:'cups'},
  {emoji:'🫙',name:'MTR instant rasam powder',nameTA:'ரசம் பொடி',nameUR:'رسم پاؤڈر',qty:1,unit:'sachet/1.5 tsp'},
  {emoji:'🍅',name:'Tomato (crushed)',nameTA:'தக்காளி',nameUR:'ٹماٹر',qty:1,unit:'small'},
  {emoji:'🟡',name:'Tamarind paste',nameTA:'புளி',nameUR:'تمر ہندی',qty:0.5,unit:'tsp'},
  {emoji:'🌿',name:'Curry leaves',nameTA:'கறிவேப்பிலை',nameUR:'کڑی پتہ',qty:4,unit:'leaves'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.5,unit:'tsp'},
  {emoji:'🥟',name:'Papad',nameTA:'அப்பளம்',nameUR:'پاپڑ',qty:1,unit:'nos'},
],
steps:[
  {text:'In AGARO kettle: add 400ml water + crushed tomato + tamarind paste + rasam powder + curry leaves + salt. Knob → **II (High)**. Boil 4–5 min.',timer:300},
  {text:'Reduce knob to **I (Low)** for 1 min. Rasam should smell fragrant — thin and tangy.',timer:60},
  {text:'Roast papad on flat pan on V-Guard 1400W for 30 sec each side (or hold over flame briefly).',timer:30},
  {text:'Pour rasam generously over rice. Mash gently. Eat with roasted papad.',timer:0},
],
tip:'MTR instant rasam powder gives authentic Chennai-style rasam. Buy sachet packs (₹5 each). Rasam rice is the ultimate comfort food — easy to digest, good for illness days.',
video:'rasam rice recipe instant south indian',
},

{id:'ls17',type:'lunch',effort:'simple',time:15,protein:18,calories:310,emoji:'🍗',
name:'Chicken Clear Soup + Rice',nameTA:'சிக்கன் சூப் சாதம்',nameUR:'چکن سوپ چاول',
equipment:['smart pot'],nightPrep:false,
ingredients:[
  {emoji:'🍗',name:'Chicken pieces (bone-in)',nameTA:'சிக்கன்',nameUR:'مرغی',qty:150,unit:'g'},
  {emoji:'🍚',name:'Cooked rice',nameTA:'சாதம்',nameUR:'چاول',qty:1.5,unit:'cups'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:0.5,unit:'nos'},
  {emoji:'🫙',name:'Ginger-garlic paste',nameTA:'இஞ்சி பூண்டு',nameUR:'ادرک لہسن',qty:1,unit:'tsp'},
  {emoji:'⚫',name:'Black pepper (crushed)',nameTA:'மிளகு',nameUR:'کالی مرچ',qty:0.5,unit:'tsp'},
  {emoji:'🌿',name:'Coriander + mint leaves',nameTA:'கொத்தமல்லி புதினா',nameUR:'دھنیا پدینہ',qty:1,unit:'tbsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.75,unit:'tsp'},
],
steps:[
  {text:'Add chicken + onion + ginger-garlic paste + black pepper + salt + 400ml water to Smart Pot.',timer:0},
  {text:'Press **Soup** → adjust to 12 min → **Start**.',timer:720},
  {text:'Natural release 5 min. Open. Add coriander + mint. The broth should be clear and fragrant.',timer:300},
  {text:'Pour hot soup over rice. Mash chicken off bones with spoon. Eat soup-soaked rice with chicken.',timer:0},
],
tip:'Bone-in chicken gives much richer soup flavor than boneless. The soup absorbs into rice making a flavorful, protein-rich meal. Add a squeeze of lime and sliced ginger on top.',
video:'chicken clear soup rice Indian style',
},

{id:'ls18',type:'lunch',effort:'simple',time:12,protein:13,calories:280,emoji:'🍜',
name:'Semiya Upma + Boiled Egg',nameTA:'சேமியா உப்மா முட்டை',nameUR:'سیمیا اوپما انڈا',
equipment:['induction','kettle'],nightPrep:false,
ingredients:[
  {emoji:'🍜',name:'Vermicelli (semiya)',nameTA:'சேமியா',nameUR:'سیمیا',qty:0.75,unit:'cup'},
  {emoji:'🥚',name:'Egg',nameTA:'முட்டை',nameUR:'انڈا',qty:1,unit:'nos'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:0.5,unit:'small'},
  {emoji:'🌶️',name:'Green chili',nameTA:'பச்சை மிளகாய்',nameUR:'ہری مرچ',qty:1,unit:'nos'},
  {emoji:'🌿',name:'Curry leaves + mustard',nameTA:'கறிவேப்பிலை கடுகு',nameUR:'کڑی پتہ رائی',qty:4,unit:'leaves + 0.25 tsp'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.5,unit:'tsp'},
],
steps:[
  {text:'Boil egg in kettle (knob → **II (High)** for 8 min). Cool and peel.',timer:480},
  {text:'Dry roast vermicelli in flat pan on V-Guard 1000W for 2–3 min until light golden. Remove and set aside.',timer:180},
  {text:'Same pan: add 1 tsp oil. Add mustard + curry leaves + onion + green chili. Sauté 2 min.',timer:120},
  {text:'Add 1.5 cups water + salt. Bring to boil on 1400W. Add roasted vermicelli. Stir. Cook covered on 800W for 3–4 min until water absorbs. Fluff with fork.',timer:240},
  {text:'Serve semiya upma with halved boiled egg on side.',timer:0},
],
tip:'Roasting vermicelli before cooking prevents sticking and adds nutty flavor. Different from breakfast semiya upma — this is a heavier lunch portion with egg protein. Excellent packed lunch.',
video:'semiya upma recipe south indian vermicelli',
},

"""

marker = '];\n\nwindow.__PANTRY__'
pos = content.find(marker)
if pos == -1:
    print('ERROR: marker not found')
else:
    content = content[:pos] + NEW + content[pos:]
    with open(r'C:\Users\Syed Asrar\bachelor-meal-plan\meals.js', 'w', encoding='utf-8') as f:
        f.write(content)
    print('Lunch simple ls7-ls18 inserted (12 recipes)')
