with open(r'C:\Users\Syed Asrar\bachelor-meal-plan\meals.js', 'r', encoding='utf-8') as f:
    content = f.read()

NEW = r"""
{id:'sm7',type:'snack',effort:'medium',time:15,protein:4,calories:160,emoji:'🌽',
name:'Corn Chaat',nameTA:'சோளம் சாட்',nameUR:'مکئی چاٹ',
equipment:['induction'],nightPrep:false,
ingredients:[
  {emoji:'🌽',name:'Sweet corn (canned or fresh boiled)',nameTA:'சோளம்',nameUR:'مکئی',qty:1,unit:'cup'},
  {emoji:'🧅',name:'Onion (finely chopped)',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:0.5,unit:'small'},
  {emoji:'🍅',name:'Tomato (finely chopped)',nameTA:'தக்காளி',nameUR:'ٹماٹر',qty:0.5,unit:'small'},
  {emoji:'🌿',name:'Coriander leaves',nameTA:'கொத்தமல்லி',nameUR:'دھنیا',qty:1,unit:'tbsp'},
  {emoji:'🫙',name:'Chaat masala + chili powder',nameTA:'சாட் மசாலா மிளகாய்',nameUR:'چاٹ مسالا مرچ',qty:0.5,unit:'tsp each'},
  {emoji:'🍋',name:'Lemon juice',nameTA:'எலுமிச்சை',nameUR:'لیموں',qty:1,unit:'tsp'},
  {emoji:'🧈',name:'Butter',nameTA:'வெண்ணெய்',nameUR:'مکھن',qty:1,unit:'tsp'},
],
steps:[
  {text:'If using canned corn: drain and rinse. If fresh: boil corn in kettle 5 min, cut off the cob.',timer:300},
  {text:'Heat flat pan on V-Guard 1200W. Add butter + corn. Toss 2–3 min until corn gets slightly charred spots.',timer:180},
  {text:'Transfer to bowl. Add onion + tomato + coriander + chaat masala + chili + lemon. Toss. Serve immediately.',timer:0},
],
tip:'American Sweet Corn (can) from supermarkets works perfectly — drain and rinse. The brief sauté in butter gives a roasted, slightly caramelized flavor. Chennai beach corn stall style.',
video:'corn chaat recipe roasted butter style',
},

{id:'sm8',type:'snack',effort:'medium',time:10,protein:14,calories:280,emoji:'🥪',
name:'Egg Sandwich',nameTA:'முட்டை சாண்ட்விச்',nameUR:'انڈا سینڈوچ',
equipment:['kettle','induction'],nightPrep:false,
ingredients:[
  {emoji:'🥚',name:'Eggs',nameTA:'முட்டை',nameUR:'انڈا',qty:2,unit:'nos'},
  {emoji:'🍞',name:'Bread slices',nameTA:'பிரட்',nameUR:'بریڈ',qty:2,unit:'slices'},
  {emoji:'🫙',name:'Mayonnaise',nameTA:'மயோனீஸ்',nameUR:'مایونیز',qty:1,unit:'tbsp'},
  {emoji:'⚫',name:'Black pepper + salt',nameTA:'மிளகு உப்பு',nameUR:'کالی مرچ نمک',qty:0.5,unit:'tsp each'},
  {emoji:'🥬',name:'Cabbage (shredded, optional)',nameTA:'முட்டைக்கோஸ்',nameUR:'گوبھی',qty:1,unit:'tbsp'},
],
steps:[
  {text:'Boil eggs in AGARO kettle (knob → **II (High)**, 10 min). Cool in water, peel.',timer:600},
  {text:'Mash eggs with fork. Mix with mayo + salt + pepper (and cabbage if using). The filling should be creamy.',timer:0},
  {text:'Spread egg filling between bread slices. Press together. Cut diagonally.',timer:0},
  {text:'Optional: toast in flat pan (V-Guard 1200W) 30 sec each side until golden.',timer:60},
],
tip:'Classic egg salad sandwich. Add a pinch of mustard powder or a drop of vinegar for a tangy twist. Can pack in tiffin box for college/office. Refrigerate filling up to 1 day.',
video:'egg sandwich recipe easy protein',
},

{id:'sm9',type:'snack',effort:'medium',time:25,protein:8,calories:200,emoji:'🍶',
name:'Dahi Vada',nameTA:'தகர வட',nameUR:'دہی وڈا',
equipment:['smart pot','frying pan'],nightPrep:true,
ingredients:[
  {emoji:'🫘',name:'Urad dal (soaked 4 hours)',nameTA:'உளுந்து',nameUR:'اڑد دال',qty:0.5,unit:'cup'},
  {emoji:'🌶️',name:'Green chili + ginger',nameTA:'பச்சை மிளகாய் இஞ்சி',nameUR:'ہری مرچ ادرک',qty:0.5,unit:'tsp each'},
  {emoji:'🍶',name:'Curd (whisked smooth)',nameTA:'தயிர்',nameUR:'دہی',qty:200,unit:'ml'},
  {emoji:'🫙',name:'Chaat masala + cumin powder',nameTA:'சாட் மசாலா சீரகம்',nameUR:'چاٹ مسالا زیرہ',qty:0.5,unit:'tsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.5,unit:'tsp'},
  {emoji:'🛢️',name:'Sunflower oil (for frying)',nameTA:'எண்ணெய்',nameUR:'تیل',qty:200,unit:'ml'},
],
steps:[
  {text:'Soak urad dal 4 hours. Grind in Inalsa food processor (blade, **2 (High)**, 1 min) with green chili + ginger + minimal water. Batter should be thick and fluffy.',timer:0},
  {text:'Add salt to batter. Beat by hand 2 min to aerate.',timer:120},
  {text:'Heat frying pan on V-Guard **Deep Fry** preset. Drop tablespoon-sized balls of batter into hot oil. Fry 3–4 min until golden. Drain.',timer:240},
  {text:'Soak fried vadas in warm water 2 min. Squeeze gently. Place in plate. Pour whisked curd generously over.',timer:120},
  {text:'Sprinkle chaat masala + cumin powder. Add tamarind chutney if available. Serve.',timer:0},
],
tip:'The trick is soaking fried vadas in water before adding curd — it makes them soft and pillowy. Beat the batter well; air makes vadas light. Prepare vadas the night before for a faster snack.',
video:'dahi vada recipe soft easy',
},

{id:'sm10',type:'snack',effort:'medium',time:20,protein:18,calories:290,emoji:'🍗',
name:'Chicken Nuggets (Pan-Fried)',nameTA:'சிக்கன் நகட்ஸ்',nameUR:'چکن نگٹس',
equipment:['induction'],nightPrep:true,
ingredients:[
  {emoji:'🍗',name:'Boneless chicken (cubed 1-inch)',nameTA:'சிக்கன்',nameUR:'مرغی',qty:150,unit:'g'},
  {emoji:'🥚',name:'Egg (beaten)',nameTA:'முட்டை',nameUR:'انڈا',qty:1,unit:'nos'},
  {emoji:'🌾',name:'Breadcrumbs / crushed cornflakes',nameTA:'பிரட் தூள்',nameUR:'بریڈ کرمب',qty:4,unit:'tbsp'},
  {emoji:'🌾',name:'Cornflour',nameTA:'கார்ன் மாவு',nameUR:'کارن فلور',qty:2,unit:'tbsp'},
  {emoji:'🔴',name:'Chili powder + pepper + garlic powder',nameTA:'மிளகாய் மிளகு பூண்டு',nameUR:'مرچ مرچ لہسن',qty:0.5,unit:'tsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.5,unit:'tsp'},
],
steps:[
  {text:'Marinate chicken cubes with chili + pepper + garlic powder + salt. Rest 15 min.',timer:900},
  {text:'Dip each piece: coat in cornflour → dip in beaten egg → roll in breadcrumbs.',timer:0},
  {text:'Heat flat pan on V-Guard 1200W. Add 2 tsp oil (shallow fry). Pan-fry nuggets 3–4 min each side until golden brown and cooked through.',timer:240},
  {text:'Drain on paper. Serve with ketchup or hot sauce.',timer:0},
],
tip:'Crush cornflakes in your hand for a crunchier coating than store breadcrumbs. Chicken cubes must be uniform size for even cooking. Pan-fry rather than deep-fry — same crunch, much less oil.',
video:'chicken nuggets pan fried homemade easy',
},

{id:'sm11',type:'snack',effort:'medium',time:20,protein:4,calories:200,emoji:'🍡',
name:'Rava Ladoo',nameTA:'ரவா லட்டு',nameUR:'سوجی لڈو',
equipment:['induction'],nightPrep:false,
ingredients:[
  {emoji:'🌾',name:'Semolina (rava/suji)',nameTA:'ரவை',nameUR:'سوجی',qty:1,unit:'cup'},
  {emoji:'🟤',name:'Sugar',nameTA:'சர்க்கரை',nameUR:'چینی',qty:0.5,unit:'cup'},
  {emoji:'🥥',name:'Grated coconut (dry)',nameTA:'தேங்காய் துருவல்',nameUR:'ناریل',qty:3,unit:'tbsp'},
  {emoji:'🌰',name:'Cashews + raisins',nameTA:'முந்திரி திராட்சை',nameUR:'کاجو کشمش',qty:1,unit:'tbsp each'},
  {emoji:'🧈',name:'Ghee',nameTA:'நெய்',nameUR:'گھی',qty:3,unit:'tbsp'},
  {emoji:'🌿',name:'Cardamom powder',nameTA:'ஏலக்காய்',nameUR:'الائچی',qty:0.25,unit:'tsp'},
  {emoji:'🥛',name:'Milk (warm, for binding)',nameTA:'பால்',nameUR:'دودھ',qty:2,unit:'tbsp'},
],
steps:[
  {text:'Heat flat pan on V-Guard 1000W. Add ghee + cashews (golden) + raisins. Remove. Add rava to same pan. Dry roast on 1000W, stirring 5–6 min until light golden and fragrant.',timer:360},
  {text:'Add coconut + sugar + cardamom. Mix on 800W for 2 min. Turn off heat. Add cashews + raisins.',timer:120},
  {text:'Add warm milk spoon by spoon, mixing. Mixture should hold shape when pressed but not be too wet.',timer:0},
  {text:'While still warm, shape into lemon-sized balls. Press firmly. Cool completely before storing.',timer:0},
],
tip:'Shape ladoos while the mixture is still warm — once cool it becomes too dry to bind. Store in airtight container up to 5 days at room temp. Makes 8–10 ladoos. Traditional sweet snack.',
video:'rava ladoo recipe easy quick',
},

{id:'sm12',type:'snack',effort:'medium',time:25,protein:3,calories:220,emoji:'🥔',
name:'Crispy Potato Wedges',nameTA:'உருளை வெஜ்கள்',nameUR:'آلو ویجز',
equipment:['induction'],nightPrep:false,
ingredients:[
  {emoji:'🥔',name:'Potato',nameTA:'உருளைக்கிழங்கு',nameUR:'آلو',qty:2,unit:'large'},
  {emoji:'🔴',name:'Chili powder + cumin + turmeric',nameTA:'மிளகாய் சீரகம் மஞ்சள்',nameUR:'مرچ زیرہ ہلدی',qty:0.5,unit:'tsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.75,unit:'tsp'},
  {emoji:'🛢️',name:'Sunflower oil',nameTA:'எண்ணெய்',nameUR:'تیل',qty:2,unit:'tbsp'},
  {emoji:'🍋',name:'Lemon juice',nameTA:'எலுமிச்சை',nameUR:'لیموں',qty:1,unit:'tsp'},
],
steps:[
  {text:'Wash potatoes well. Cut into wedges (8 per potato — cut in half, then each half into 4). No need to peel.',timer:0},
  {text:'Toss wedges with oil + chili + cumin + turmeric + salt in bowl. Coat well.',timer:0},
  {text:'Heat flat pan on V-Guard 1400W. Place wedges in single layer. Cook 5–6 min until one side is golden. Flip.',timer:360},
  {text:'Cook other side 4–5 min. Reduce to 1200W if browning too fast. Should be crispy outside, soft inside.',timer:300},
  {text:'Squeeze lemon. Serve with ketchup or green chutney.',timer:0},
],
tip:'Do not crowd the pan — wedges need contact with hot pan to crisp. Cooking skin-on gives extra crunch and fiber. Parboiling 5 min first makes the inside fluffier — optional but good.',
video:'potato wedges pan fried crispy Indian spices',
},

{id:'sm13',type:'snack',effort:'medium',time:10,protein:3,calories:150,emoji:'🍱',
name:'Fruit Chaat',nameTA:'பழம் சாட்',nameUR:'پھل چاٹ',
equipment:[],nightPrep:false,
ingredients:[
  {emoji:'🍎',name:'Apple',nameTA:'ஆப்பிள்',nameUR:'سیب',qty:0.5,unit:'nos'},
  {emoji:'🍌',name:'Banana',nameTA:'வாழைப்பழம்',nameUR:'کیلا',qty:1,unit:'nos'},
  {emoji:'🍇',name:'Grapes / pomegranate',nameTA:'திராட்சை',nameUR:'انگور',qty:10,unit:'nos'},
  {emoji:'🥭',name:'Mango (seasonal) or papaya',nameTA:'மாம்பழம்',nameUR:'آم',qty:0.25,unit:'cup'},
  {emoji:'🫙',name:'Chaat masala',nameTA:'சாட் மசாலா',nameUR:'چاٹ مسالا',qty:0.5,unit:'tsp'},
  {emoji:'🍋',name:'Lemon juice',nameTA:'எலுமிச்சை',nameUR:'لیموں',qty:1,unit:'tsp'},
  {emoji:'⚫',name:'Black pepper + salt',nameTA:'மிளகு உப்பு',nameUR:'کالی مرچ نمک',qty:1,unit:'pinch each'},
],
steps:[
  {text:'Chop all fruits into 1-inch pieces. Mix in a bowl.',timer:0},
  {text:'Sprinkle chaat masala + black pepper + salt. Squeeze lemon. Toss gently.',timer:0},
  {text:'Serve immediately — fruit chaat is best fresh.',timer:0},
],
tip:'Use whatever seasonal fruit is available in Chennai. Chaat masala + lemon transforms bland fruit into something exciting. Add a spoon of fresh curd on the side for protein. Great Ramadan iftar snack.',
video:'fruit chaat recipe Indian spiced',
},

{id:'sm14',type:'snack',effort:'medium',time:20,protein:6,calories:180,emoji:'🌿',
name:'Methi Pakora',nameTA:'வெந்தய இலை பஜ்ஜி',nameUR:'میتھی پکوڑا',
equipment:['frying pan'],nightPrep:false,
ingredients:[
  {emoji:'🌿',name:'Methi leaves (fenugreek)',nameTA:'வெந்தய இலை',nameUR:'میتھی',qty:1,unit:'cup packed'},
  {emoji:'🌾',name:'Besan (gram flour)',nameTA:'கடலை மாவு',nameUR:'بیسن',qty:0.5,unit:'cup'},
  {emoji:'🌶️',name:'Green chili (minced)',nameTA:'பச்சை மிளகாய்',nameUR:'ہری مرچ',qty:1,unit:'nos'},
  {emoji:'🟡',name:'Turmeric + chili powder + cumin',nameTA:'மஞ்சள் மிளகாய் சீரகம்',nameUR:'ہلدی مرچ زیرہ',qty:0.25,unit:'tsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.5,unit:'tsp'},
  {emoji:'🛢️',name:'Oil (deep frying)',nameTA:'எண்ணெய்',nameUR:'تیل',qty:200,unit:'ml'},
],
steps:[
  {text:'Wash methi leaves. Mix besan + green chili + turmeric + chili + cumin + salt. Add water gradually to make thick batter (not runny).',timer:0},
  {text:'Add methi leaves to batter. Mix until leaves are coated.',timer:0},
  {text:'Heat frying pan on V-Guard **Deep Fry** preset. Test with drop of batter — it should rise immediately.',timer:120},
  {text:'Drop tablespoon-sized portions into hot oil. Fry 3–4 min until golden and crispy. Drain on paper.',timer:240},
  {text:'Serve hot with green chutney or ketchup. Pairs perfectly with chai.',timer:0},
],
tip:'Methi leaves have a slight bitterness that adds character to pakoras. Add a pinch of soda bicarb (baking soda) to batter for extra puffiness. Eat immediately — pakoras lose crunch quickly.',
video:'methi pakora recipe fenugreek fritters',
},

{id:'sm15',type:'snack',effort:'medium',time:20,protein:5,calories:190,emoji:'🧅',
name:'Onion Pakora (Bhajji)',nameTA:'வெங்காய பஜ்ஜி',nameUR:'پیاز پکوڑا',
equipment:['frying pan'],nightPrep:false,
ingredients:[
  {emoji:'🧅',name:'Onion (thinly sliced)',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:2,unit:'medium'},
  {emoji:'🌾',name:'Besan (gram flour)',nameTA:'கடலை மாவு',nameUR:'بیسن',qty:0.5,unit:'cup'},
  {emoji:'🌶️',name:'Green chili (sliced)',nameTA:'பச்சை மிளகாய்',nameUR:'ہری مرچ',qty:1,unit:'nos'},
  {emoji:'🌿',name:'Curry leaves + coriander',nameTA:'கறிவேப்பிலை கொத்தமல்லி',nameUR:'کڑی پتہ دھنیا',qty:4,unit:'leaves + 1 tbsp'},
  {emoji:'🔴',name:'Chili powder + turmeric',nameTA:'மிளகாய் மஞ்சள்',nameUR:'مرچ ہلدی',qty:0.25,unit:'tsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.5,unit:'tsp'},
  {emoji:'🛢️',name:'Oil (deep frying)',nameTA:'எண்ணெய்',nameUR:'تیل',qty:200,unit:'ml'},
],
steps:[
  {text:'Mix sliced onion + salt. Squeeze firmly — onion releases water. This is the liquid for the batter.',timer:0},
  {text:'Add besan + green chili + curry leaves + coriander + chili + turmeric to squeezed onion. Mix — the natural onion water should make a thick batter without adding extra water.',timer:0},
  {text:'Heat frying pan on V-Guard **Deep Fry** preset. Test oil with small batter drop.',timer:120},
  {text:'Drop fistfuls of batter into oil. Fry 3–4 min until golden and crispy. Drain.',timer:240},
  {text:'Serve immediately with green chutney + hot chai.',timer:0},
],
tip:'Onion bajji (pakkoda) is the most beloved rainy-day snack in South India. Key trick: use onion water as the only liquid — adding extra water makes soggy bajji. Thin onion slices fry better than thick.',
video:'onion pakora recipe South Indian bhajji',
},

{id:'sm16',type:'snack',effort:'medium',time:15,protein:8,calories:220,emoji:'🍞',
name:'Bread Cutlet',nameTA:'பிரட் கட்லட்',nameUR:'بریڈ کٹلٹ',
equipment:['induction'],nightPrep:false,
ingredients:[
  {emoji:'🍞',name:'Bread slices (2-day-old)',nameTA:'பிரட்',nameUR:'بریڈ',qty:4,unit:'slices'},
  {emoji:'🥔',name:'Potato (boiled, mashed)',nameTA:'உருளைக்கிழங்கு',nameUR:'آلو',qty:1,unit:'medium'},
  {emoji:'🧅',name:'Onion (chopped)',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:0.5,unit:'small'},
  {emoji:'🌶️',name:'Green chili + ginger',nameTA:'பச்சை மிளகாய் இஞ்சி',nameUR:'ہری مرچ ادرک',qty:0.5,unit:'tsp each'},
  {emoji:'🌿',name:'Coriander + chaat masala',nameTA:'கொத்தமல்லி சாட்',nameUR:'دھنیا چاٹ',qty:1,unit:'tbsp + 0.5 tsp'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.5,unit:'tsp'},
],
steps:[
  {text:'Mix mashed potato + onion + green chili + ginger + coriander + chaat masala + salt. Divide into 4 equal portions.',timer:0},
  {text:'Dip bread slice in water briefly (1 sec). Squeeze out excess water firmly — bread should be damp but not dripping.',timer:0},
  {text:'Place one potato portion on damp bread. Fold bread around filling, shape into flat oval. Press firmly to seal.',timer:0},
  {text:'Heat flat pan on V-Guard 1200W. Add 2 tsp oil. Shallow fry each cutlet 2–3 min per side until golden and crispy.',timer:300},
  {text:'Serve with ketchup or mint chutney.',timer:0},
],
tip:'Bread cutlets are a brilliant way to use stale bread. The brief water dip makes bread pliable without making it soggy. Press firmly while shaping — loose cutlets break in the pan.',
video:'bread cutlet recipe easy Indian snack',
},

{id:'sm17',type:'snack',effort:'medium',time:25,protein:4,calories:200,emoji:'🥔',
name:'Aloo Tikki',nameTA:'உருளை டிக்கி',nameUR:'آلو ٹکی',
equipment:['induction'],nightPrep:false,
ingredients:[
  {emoji:'🥔',name:'Potato (boiled, mashed)',nameTA:'உருளைக்கிழங்கு',nameUR:'آلو',qty:3,unit:'medium'},
  {emoji:'🌿',name:'Coriander + green chili',nameTA:'கொத்தமல்லி பச்சை மிளகாய்',nameUR:'دھنیا ہری مرچ',qty:2,unit:'tbsp + 1 nos'},
  {emoji:'🫙',name:'Chaat masala + cumin + amchur',nameTA:'சாட் மசாலா சீரகம்',nameUR:'چاٹ مسالا زیرہ آم چور',qty:0.5,unit:'tsp each'},
  {emoji:'🌾',name:'Cornflour (binding)',nameTA:'கார்ன் மாவு',nameUR:'کارن فلور',qty:2,unit:'tbsp'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.5,unit:'tsp'},
],
steps:[
  {text:'Mix mashed potato + coriander + green chili + chaat masala + cumin + amchur + cornflour + salt. Knead briefly.',timer:0},
  {text:'Divide into 6 equal balls. Flatten each into 1/2 inch thick round tikki.',timer:0},
  {text:'Heat flat pan on V-Guard 1200W. Add 2 tsp oil. Place tikkis. Cook 3–4 min until bottom is golden and crispy. Flip.',timer:240},
  {text:'Cook other side 3 min. Both sides should be crispy gold. Serve hot with tamarind chutney + curd.',timer:180},
],
tip:'Potatoes must be fully dry — steam after boiling to remove moisture. Moisture = soft tikki. Cornflour gives the crispy crust. Refrigerate shaped raw tikkis 20 min before frying for better results.',
video:'aloo tikki recipe crispy Delhi style',
},

{id:'sm18',type:'snack',effort:'medium',time:25,protein:8,calories:290,emoji:'🍛',
name:'Mini Pav Bhaji',nameTA:'பாவ் பாஜி',nameUR:'پاؤ بھاجی',
equipment:['induction'],nightPrep:false,
ingredients:[
  {emoji:'🥔',name:'Potato + cauliflower (boiled)',nameTA:'உருளை காலிஃப்ளவர்',nameUR:'آلو گوبھی',qty:1,unit:'cup mixed'},
  {emoji:'🍅',name:'Tomato',nameTA:'தக்காளி',nameUR:'ٹماٹر',qty:2,unit:'nos'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:1,unit:'medium'},
  {emoji:'🧈',name:'Butter',nameTA:'வெண்ணெய்',nameUR:'مکھن',qty:2,unit:'tbsp'},
  {emoji:'🫙',name:'Pav bhaji masala',nameTA:'பாவ் பாஜி மசாலா',nameUR:'پاؤ بھاجی مسالا',qty:1.5,unit:'tsp'},
  {emoji:'🫙',name:'Pav buns',nameTA:'பாவ்',nameUR:'پاؤ',qty:2,unit:'nos'},
  {emoji:'🧂',name:'Salt + coriander + lemon',nameTA:'உப்பு',nameUR:'نمک دھنیا لیموں',qty:0.5,unit:'tsp'},
],
steps:[
  {text:'Boil potato + cauliflower in Smart Pot (Steam 8 min). Mash roughly.',timer:480},
  {text:'Heat flat pan on V-Guard 1400W. Add 1 tbsp butter. Fry onion 3 min until golden. Add chopped tomato + pav bhaji masala + salt. Cook 3 min until tomato is mushy.',timer:360},
  {text:'Add mashed vegetables. Mash everything together with back of spoon. Add 50ml water. Cook 5 min stirring until thick. Add lemon + coriander.',timer:300},
  {text:'Slice pav buns. Toast in remaining butter on pan 1 min cut-side down. Serve hot bhaji alongside toasted pav.',timer:60},
],
tip:'Pav bhaji masala (MDH or Everest brand, ₹30) is the essential spice here — do not substitute. Mash the bhaji well for the right texture. The butter-toasted pav is non-negotiable for authentic taste.',
video:'pav bhaji recipe easy home style Mumbai',
},

"""

marker = '];\n\nwindow.__PANTRY__'
pos = content.find(marker)
if pos == -1:
    print('ERROR: marker not found')
else:
    content = content[:pos] + NEW + content[pos:]
    with open(r'C:\Users\Syed Asrar\bachelor-meal-plan\meals.js', 'w', encoding='utf-8') as f:
        f.write(content)
    print('Snack medium sm7-sm18 inserted (12 recipes)')
