with open(r'C:\Users\Syed Asrar\bachelor-meal-plan\meals.js', 'r', encoding='utf-8') as f:
    content = f.read()

NEW = r"""
{id:'bh9',type:'breakfast',effort:'hard',time:35,protein:12,calories:430,emoji:'🫓',
name:'Puri + Aloo Bhaji',nameTA:'பூரி உருளை மசியல்',nameUR:'پوری آلو بھاجی',
equipment:['induction','frying pan'],nightPrep:false,
ingredients:[
  {emoji:'🌾',name:'Aashirvaad atta (whole wheat)',nameTA:'கோதுமை மாவு',nameUR:'گندم آٹا',qty:0.75,unit:'cup'},
  {emoji:'🥔',name:'Potato (boiled)',nameTA:'உருளைக்கிழங்கு',nameUR:'آلو',qty:2,unit:'medium'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:1,unit:'small'},
  {emoji:'🟡',name:'Turmeric + mustard seeds',nameTA:'மஞ்சள் கடுகு',nameUR:'ہلدی رائی',qty:0.25,unit:'tsp each'},
  {emoji:'🌶️',name:'Green chili',nameTA:'பச்சை மிளகாய்',nameUR:'ہری مرچ',qty:1,unit:'nos'},
  {emoji:'🛢️',name:'Sunflower oil (deep frying)',nameTA:'எண்ணெய்',nameUR:'تیل',qty:200,unit:'ml'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.75,unit:'tsp'},
],
steps:[
  {text:'Boil potatoes in Smart Pot: Press **Steam** → 10 min → **Start**. Natural release 5 min. Peel and roughly mash.',timer:600},
  {text:'Bhaji: heat flat pan on V-Guard 1200W. Add 1 tsp oil. Add mustard seeds (wait to splutter) + sliced onion + green chili. Sauté 2 min. Add potatoes + turmeric + salt. Mash and mix. 3 min on 1000W. Keep warm.',timer:300},
  {text:'Puri dough: mix atta + 0.25 tsp salt + water to stiff dough. Knead 3 min (or Inalsa kneading blade **2 (High)** 60 sec). Divide into 6 balls. Roll each into small circle.',timer:180},
  {text:'Heat frying pan on V-Guard **Deep Fry** preset. Add oil (2 inch depth). Test oil: drop small dough — if it rises immediately, oil is ready.',timer:120},
  {text:'Slide puri into hot oil. Press gently with spatula so it puffs. Fry 20–30 sec per side until golden. Drain on paper. Fry all 6 puris.',timer:180},
  {text:'Serve 3 puris per serving with aloo bhaji on side.',timer:0},
],
tip:'Puri dough must be stiffer than chapati dough. Oil must be hot enough — cool oil makes soggy puris. Bhaji can be made night before and reheated.',
video:'puri aloo bhaji recipe south indian breakfast',
},

{id:'bh10',type:'breakfast',effort:'hard',time:30,protein:14,calories:360,emoji:'🫓',
name:'Methi Paratha',nameTA:'வெந்தய இலை பராத்தா',nameUR:'میتھی پراٹھا',
equipment:['flat pan','food processor'],nightPrep:true,
ingredients:[
  {emoji:'🌾',name:'Aashirvaad atta',nameTA:'கோதுமை மாவு',nameUR:'گندم آٹا',qty:1,unit:'cup'},
  {emoji:'🌿',name:'Fresh methi (fenugreek leaves)',nameTA:'வெந்தய இலை',nameUR:'میتھی پتہ',qty:0.5,unit:'cup packed'},
  {emoji:'🧅',name:'Onion (finely chopped)',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:0.5,unit:'small'},
  {emoji:'🌶️',name:'Green chili + ginger (minced)',nameTA:'பச்சை மிளகாய் இஞ்சி',nameUR:'ہری مرچ ادرک',qty:0.5,unit:'tsp each'},
  {emoji:'🟡',name:'Turmeric + cumin powder',nameTA:'மஞ்சள் சீரகப்பொடி',nameUR:'ہلدی زیرہ',qty:0.25,unit:'tsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.75,unit:'tsp'},
  {emoji:'🧈',name:'Ghee or butter',nameTA:'நெய்',nameUR:'گھی',qty:2,unit:'tsp'},
],
steps:[
  {text:'Wash and roughly chop methi leaves. Mix atta + methi + onion + green chili + ginger + turmeric + cumin + salt. Add water to make soft dough.',timer:0},
  {text:'Knead dough 3 min by hand (or Inalsa kneading blade on **2 (High)** 60 sec). Rest 10 min covered.',timer:600},
  {text:'Divide into 4 balls. Roll each into thin round paratha (flour board).',timer:0},
  {text:'Heat flat pan on V-Guard 1600W. Cook paratha 1 min until bubbles appear. Flip. Apply 0.5 tsp ghee on cooked side. Flip again.',timer:60},
  {text:'Apply ghee on second side. Press gently with spatula. Cook 30 sec until both sides have golden spots. Repeat for all 4.',timer:30},
  {text:'Serve hot with curd or pickle.',timer:0},
],
tip:'Fresh methi available in Koyambedu market or local veggie shops (₹10/bunch). Methi is slightly bitter — salt in dough reduces bitterness. Excellent for blood sugar and digestion.',
video:'methi paratha recipe soft fenugreek paratha',
},

{id:'bh11',type:'breakfast',effort:'hard',time:35,protein:14,calories:380,emoji:'🥞',
name:'Masala Dosa (Stuffed)',nameTA:'மசாலா தோசை',nameUR:'مسالا ڈوسہ',
equipment:['flat pan','induction'],nightPrep:false,
ingredients:[
  {emoji:'🍚',name:'Ready-made dosa batter',nameTA:'தோசை மாவு',nameUR:'ڈوسہ بیٹر',qty:4,unit:'ladles'},
  {emoji:'🥔',name:'Potato (boiled, mashed)',nameTA:'உருளைக்கிழங்கு',nameUR:'آلو',qty:2,unit:'medium'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:1,unit:'medium'},
  {emoji:'🌶️',name:'Green chili',nameTA:'பச்சை மிளகாய்',nameUR:'ہری مرچ',qty:1,unit:'nos'},
  {emoji:'🟡',name:'Turmeric + mustard seeds + curry leaves',nameTA:'மஞ்சள் கடுகு',nameUR:'ہلدی رائی کڑی پتہ',qty:0.25,unit:'tsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.75,unit:'tsp'},
],
steps:[
  {text:'Potato masala: boil potatoes in Smart Pot (Steam 10 min). Mash. Heat flat pan 1200W, add oil + mustard + curry leaves + sliced onion + green chili + turmeric. Sauté 2 min. Add potato + salt. Mix well. Set aside.',timer:600},
  {text:'Heat flat pan on V-Guard 1600W (very hot). Sprinkle water — it should evaporate instantly. Reduce to 1200W.',timer:60},
  {text:'Pour one ladle dosa batter. Spread in wide thin circle (use spoon back in outward circles).',timer:0},
  {text:'Drizzle oil on edges. Cook 2 min until underside is golden. Place 2 tbsp potato masala along center line. Fold dosa over filling.',timer:120},
  {text:'Slide out. Serve with coconut chutney and sambar. Make 2–3 dosas total.',timer:0},
],
tip:'The potato masala can be made the night before and refrigerated. Pan must be very hot before pouring batter — this is the key to crispy dosa. Wipe pan with half onion between dosas.',
video:'masala dosa recipe south indian crispy',
},

{id:'bh12',type:'breakfast',effort:'hard',time:30,protein:22,calories:380,emoji:'🍗',
name:'Chicken Ghee Roast Toast',nameTA:'சிக்கன் நெய் வறுவல் டோஸ்ட்',nameUR:'چکن گھی روسٹ ٹوسٹ',
equipment:['induction','smart pot'],nightPrep:true,
ingredients:[
  {emoji:'🍗',name:'Boneless chicken (shredded)',nameTA:'சிக்கன்',nameUR:'مرغی',qty:150,unit:'g'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:1,unit:'small'},
  {emoji:'🍅',name:'Tomato',nameTA:'தக்காளி',nameUR:'ٹماٹر',qty:1,unit:'small'},
  {emoji:'🔴',name:'Kashmiri chili powder + coriander powder',nameTA:'கஷ்மீரி மிளகாய்',nameUR:'کشمیری مرچ دھنیا',qty:0.5,unit:'tsp each'},
  {emoji:'🧈',name:'Ghee',nameTA:'நெய்',nameUR:'گھی',qty:1,unit:'tsp'},
  {emoji:'🍞',name:'Bread slices',nameTA:'பிரட்',nameUR:'بریڈ',qty:2,unit:'slices'},
  {emoji:'🧂',name:'Salt + ginger-garlic paste',nameTA:'உப்பு இஞ்சி பூண்டு',nameUR:'نمک ادرک لہسن',qty:0.5,unit:'tsp each'},
],
steps:[
  {text:'Night: boil chicken in Smart Pot (Meat 12 min). Shred. Refrigerate.',timer:720},
  {text:'Morning: heat flat pan on V-Guard 1400W. Add ghee. Add sliced onion. Fry until golden brown (3–4 min).',timer:240},
  {text:'Add ginger-garlic paste. Stir 30 sec. Add chopped tomato + chili powder + coriander + salt. Cook 2 min until masala comes together.',timer:120},
  {text:'Add shredded chicken. Toss on high heat 2–3 min until chicken is coated and slightly roasted. Keep slightly dry.',timer:180},
  {text:'Toast bread on same pan edges. Top with chicken ghee roast. Serve hot.',timer:60},
],
tip:'Ghee gives the roast its rich aroma — use at least 1 tsp. Kashmiri chili gives a beautiful red color without much heat. Use leftover dinner chicken for this — zero waste.',
video:'chicken ghee roast recipe Mangalore style',
},

{id:'bh13',type:'breakfast',effort:'hard',time:30,protein:16,calories:340,emoji:'🌾',
name:'Dalia Khichdi (Broken Wheat)',nameTA:'தாளிய கோதுமை கிச்சடி',nameUR:'دلیہ کھچڑی',
equipment:['smart pot'],nightPrep:false,
ingredients:[
  {emoji:'🌾',name:'Broken wheat (dalia)',nameTA:'கோதுமை ரவை',nameUR:'دلیہ',qty:0.5,unit:'cup'},
  {emoji:'🫘',name:'Moong dal (split)',nameTA:'பாசிப்பருப்பு',nameUR:'موٹ دال',qty:2,unit:'tbsp'},
  {emoji:'🥕',name:'Carrot + peas (frozen OK)',nameTA:'கேரட் பட்டாணி',nameUR:'گاجر مٹر',qty:0.25,unit:'cup each'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:0.5,unit:'small'},
  {emoji:'🟡',name:'Turmeric + cumin',nameTA:'மஞ்சள் சீரகம்',nameUR:'ہلدی زیرہ',qty:0.25,unit:'tsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.75,unit:'tsp'},
  {emoji:'🧈',name:'Ghee',nameTA:'நெய்',nameUR:'گھی',qty:1,unit:'tsp'},
],
steps:[
  {text:'Press **Sauté** → **Start** on Smart Pot. Add ghee. Sauté cumin + onion 2 min until onion softens. Press **Cancel**.',timer:120},
  {text:'Add washed dalia + moong dal + carrots + peas + turmeric + salt + 2 cups water. Stir.',timer:0},
  {text:'Close lid. Press **Bean** → adjust to 12 min → **Start**.',timer:720},
  {text:'Natural release 5 min. Open lid. Stir well. Consistency should be porridge-like — add hot water and stir if too thick.',timer:300},
  {text:'Serve hot with a spoon of ghee on top and pickle on side.',timer:0},
],
tip:'Dalia khichdi is extremely filling and nutritious — high fiber, slow-digesting carbs, good protein from moong dal. Can be made savory or sweet (add jaggery instead of salt).',
video:'dalia khichdi recipe broken wheat porridge',
},

{id:'bh14',type:'breakfast',effort:'hard',time:35,protein:26,calories:400,emoji:'🥚',
name:'Prawn Omelette',nameTA:'இறால் ஆம்லெட்',nameUR:'جھینگا آملیٹ',
equipment:['flat pan'],nightPrep:false,
ingredients:[
  {emoji:'🦐',name:'Small prawns (cleaned)',nameTA:'சிறிய இறால்',nameUR:'جھینگا',qty:80,unit:'g'},
  {emoji:'🥚',name:'Eggs',nameTA:'முட்டை',nameUR:'انڈا',qty:3,unit:'nos'},
  {emoji:'🧅',name:'Onion (chopped)',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:0.5,unit:'small'},
  {emoji:'🍅',name:'Tomato (chopped)',nameTA:'தக்காளி',nameUR:'ٹماٹر',qty:0.5,unit:'small'},
  {emoji:'🌶️',name:'Green chili + curry leaves',nameTA:'பச்சை மிளகாய்',nameUR:'ہری مرچ کڑی پتہ',qty:1,unit:'each'},
  {emoji:'🔴',name:'Chili powder + turmeric',nameTA:'மிளகாய் பொடி மஞ்சள்',nameUR:'لال مرچ ہلدی',qty:0.25,unit:'tsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.5,unit:'tsp'},
],
steps:[
  {text:'Clean prawns (remove shell, devein). Marinate with pinch of turmeric + chili powder + salt for 5 min.',timer:300},
  {text:'Heat flat pan on V-Guard 1400W. Add 1 tsp oil. Add curry leaves + onion. Sauté 1 min. Add prawns. Cook 2–3 min until pink and curled. Set aside.',timer:180},
  {text:'Beat 3 eggs with salt + tomato + green chili in bowl.',timer:0},
  {text:'Add 1 tsp oil to pan on 1200W. Pour egg mixture. Let set 30 sec. Place prawn filling on one half. Fold omelette over. Cook 1–2 min until eggs are fully set.',timer:90},
  {text:'Serve hot. Pairs with bread or roti.',timer:0},
],
tip:'Fresh small prawns from Chennai markets (Koyambedu or local fish stalls) cost ₹150–200/250g. Prawns cook very fast — overcooked prawns become rubbery. 2–3 min is enough.',
video:'prawn omelette recipe Kerala style',
},

{id:'bh15',type:'breakfast',effort:'hard',time:30,protein:24,calories:420,emoji:'🫔',
name:'Chicken Keema Pav',nameTA:'சிக்கன் கீமா பாவ்',nameUR:'چکن قیمہ پاؤ',
equipment:['induction','smart pot'],nightPrep:true,
ingredients:[
  {emoji:'🍗',name:'Minced chicken (keema)',nameTA:'சிக்கன் கீமா',nameUR:'چکن قیمہ',qty:150,unit:'g'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:1,unit:'medium'},
  {emoji:'🍅',name:'Tomato',nameTA:'தக்காளி',nameUR:'ٹماٹر',qty:1,unit:'medium'},
  {emoji:'🫙',name:'Ginger-garlic paste',nameTA:'இஞ்சி பூண்டு விழுது',nameUR:'ادرک لہسن پیسٹ',qty:1,unit:'tsp'},
  {emoji:'🔴',name:'Chili + garam masala + cumin',nameTA:'மிளகாய் கரம் மசாலா',nameUR:'مرچ گرم مسالا زیرہ',qty:0.5,unit:'tsp each'},
  {emoji:'🫙',name:'Pav buns',nameTA:'பாவ்',nameUR:'پاؤ',qty:2,unit:'nos'},
  {emoji:'🧂',name:'Salt + coriander leaves',nameTA:'உப்பு கொத்தமல்லி',nameUR:'نمک دھنیا',qty:0.5,unit:'tsp each'},
],
steps:[
  {text:'Night prep: heat flat pan 1400W. Add oil + onion. Fry 3 min until golden. Add ginger-garlic paste, stir 30 sec. Add chopped tomato + all spices + salt. Cook 2 min.',timer:360},
  {text:'Add minced chicken. Break lumps with spoon. Cook 8–10 min on 1200W, stirring, until keema is fully cooked (no pink). Add coriander. Refrigerate.',timer:600},
  {text:'Morning: reheat keema in pan on 800W, 3–4 min. Add splash of water if dry.',timer:240},
  {text:'Slice pav buns horizontally. Toast cut side down on pan 1 min. Stuff with hot keema. Serve immediately.',timer:60},
],
tip:'Ask your butcher to mince fresh chicken. Keema makes a fast filling breakfast — high protein, easy to eat on the go. Night prep makes this 5 min in the morning.',
video:'chicken keema pav recipe Bombay style',
},

{id:'ds15',type:'dinner',effort:'simple',time:15,protein:8,calories:290,emoji:'🍅',
name:'Tomato Rice',nameTA:'தக்காளி சாதம்',nameUR:'ٹماٹر چاول',
equipment:['induction','smart pot'],nightPrep:false,
ingredients:[
  {emoji:'🍚',name:'Cooked rice (leftover)',nameTA:'சாதம்',nameUR:'چاول',qty:1.5,unit:'cups'},
  {emoji:'🍅',name:'Tomato',nameTA:'தக்காளி',nameUR:'ٹماٹر',qty:2,unit:'medium'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:0.5,unit:'medium'},
  {emoji:'🌿',name:'Curry leaves + mustard seeds',nameTA:'கறிவேப்பிலை கடுகு',nameUR:'کڑی پتہ رائی',qty:4,unit:'leaves + 0.25 tsp'},
  {emoji:'🔴',name:'Chili powder + turmeric + sambar powder',nameTA:'மிளகாய் மஞ்சள்',nameUR:'مرچ ہلدی سمبر',qty:0.5,unit:'tsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.75,unit:'tsp'},
  {emoji:'🛢️',name:'Sunflower oil',nameTA:'எண்ணெய்',nameUR:'تیل',qty:1,unit:'tsp'},
],
steps:[
  {text:'Heat flat pan on V-Guard 1200W. Add oil. Add mustard seeds (let splutter) + curry leaves + sliced onion. Sauté 2 min.',timer:120},
  {text:'Add chopped tomatoes + chili powder + turmeric + sambar powder + salt. Cook 4–5 min until tomatoes break down into thick paste.',timer:300},
  {text:'Add cooked rice. Toss gently to coat every grain with tomato masala. Mix on 800W for 2 min.',timer:120},
  {text:'Serve hot with papad and curd on side.',timer:0},
],
tip:'Perfect use of leftover rice. Tomatoes must be cooked until fully mushy — this creates the sauce that coats the rice. Squeeze lemon at the end for freshness.',
video:'tomato rice recipe south indian thakkali sadam',
},

{id:'ds16',type:'dinner',effort:'simple',time:18,protein:22,calories:380,emoji:'🥚',
name:'Egg Pepper Fry + Rice',nameTA:'முட்டை மிளகு வறுவல் சாதம்',nameUR:'انڈا کالی مرچ فرائی چاول',
equipment:['induction','smart pot'],nightPrep:false,
ingredients:[
  {emoji:'🥚',name:'Eggs (hard boiled)',nameTA:'முட்டை',nameUR:'انڈا',qty:3,unit:'nos'},
  {emoji:'🍚',name:'Cooked rice',nameTA:'சாதம்',nameUR:'چاول',qty:1.5,unit:'cups'},
  {emoji:'🧅',name:'Onion',nameTA:'வெங்காயம்',nameUR:'پیاز',qty:1,unit:'medium'},
  {emoji:'⚫',name:'Black pepper (coarsely ground)',nameTA:'மிளகு',nameUR:'کالی مرچ',qty:1,unit:'tsp'},
  {emoji:'🌿',name:'Curry leaves',nameTA:'கறிவேப்பிலை',nameUR:'کڑی پتہ',qty:6,unit:'leaves'},
  {emoji:'🔴',name:'Chili powder + turmeric',nameTA:'மிளகாய் மஞ்சள்',nameUR:'مرچ ہلدی',qty:0.25,unit:'tsp each'},
  {emoji:'🧂',name:'Salt',nameTA:'உப்பு',nameUR:'نمک',qty:0.5,unit:'tsp'},
],
steps:[
  {text:'Boil eggs in AGARO kettle: Knob → **II (High)** for 10 min. Cool, peel. Score each egg with 3–4 shallow cuts (helps masala penetrate).',timer:600},
  {text:'Heat flat pan on V-Guard 1400W. Add 1.5 tsp oil. Add curry leaves + sliced onion. Fry 3–4 min until golden.',timer:240},
  {text:'Add chili powder + turmeric + black pepper + salt. Stir 30 sec. Add eggs. Toss to coat. Fry 2–3 min — eggs should get slightly golden crust.',timer:180},
  {text:'Serve pepper eggs on a bed of plain rice. Mix gently and eat.',timer:0},
],
tip:'Score the eggs before frying — masala gets inside the cuts giving intense flavor in every bite. This is a classic Tamil Nadu thattukada (roadside stall) dish. Use freshly ground pepper for best flavor.',
video:'egg pepper fry south indian recipe muttai milagu',
},

"""

marker = '];\n\nwindow.__PANTRY__'
pos = content.find(marker)
if pos == -1:
    print('ERROR: marker not found')
else:
    content = content[:pos] + NEW + content[pos:]
    with open(r'C:\Users\Syed Asrar\bachelor-meal-plan\meals.js', 'w', encoding='utf-8') as f:
        f.write(content)
    print('Batch 3 done — breakfast hard bh9-bh15 + dinner simple ds15-ds16 inserted')
